<a href="https://colab.research.google.com/github/IagoAlmeida-ias/Programa-o-em-int-arti-generativa/blob/main/classificacao_e_avaliacao_de_modelos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Colote e Criação de Base de Dados
import pandas as pd

# 0 - E-mail Normal | 1 = SPAM
df_emails = pd.read_csv('base_emails_100.csv')

print("Visualizando os primeiros 5 e-mails da base de dados:\n")
display(df_emails.head())

tabela_emails = pd.DataFrame(df_emails)
display(tabela_emails)

Visualizando os primeiros 5 e-mails da base de dados:

                                            Mensagem  Spam
0  Promoção imperdível, compre agora e ganhe aces...     1
1   Desconto de 99% em smartphones, estoque limitado     1
2    Método comprovado para ganhar R$ 5.000 dormindo     1
3          Por favor, revise a apresentação sobre RH     0
4             Lembrete: evento corporativo no dia 20     0

                                             Mensagem  Spam
0   Promoção imperdível, compre agora e ganhe aces...     1
1    Desconto de 99% em smartphones, estoque limitado     1
2     Método comprovado para ganhar R$ 5.000 dormindo     1
3           Por favor, revise a apresentação sobre RH     0
4              Lembrete: evento corporativo no dia 20     0
..                                                ...   ...
95  Oferta especial só hoje, clique para ganhar bô...     1
96   Desconto de 50% em smartphones, estoque limitado     1
97                   Ata da reunião de ontem sobre RH     0
98  Última chance para resgatar seu prêmio em dinh...     1
99  Ganhe um vale-compras grátis respondendo a est...     1

[100 rows x 2 columns]

In [4]:
# 2. Separando /dados de Estudo e de Prova
from sklearn.model_selection import train_test_split

X = tabela_emails['Mensagem'] # O que a IA vai ler
y = tabela_emails['Spam'] # A resposta certa

# Separando 20% 90.2) para o teste final
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"E-mails para treinar: {len(X_treino)}")
print(f"E-mails escondidos para prova: {len(X_teste)}")

E-mails para treinar: 80
E-mails escondidos para prova: 20

In [5]:
# 3. Pré-processsamento (Vetorização)
from sklearn.feature_extraction.text import CountVectorizer

# Cria o nosso tradutor de texto para números
tradutor = CountVectorizer()

# Ensina o tradutor com os texto de treino e já faz a tradução
X_treino_numeros = tradutor.fit_transform(X_treino)

# Traduz também os textos da prova (sem ensinar palavras novas)
X_teste_numeros = tradutor.transform(X_teste)

print("A máquina não lê textos, ela lê matrizes assim:")
print(X_treino_numeros.toarray())

A máquina não lê textos, ela lê matrizes assim:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [6]:
# 4. Treinar e Avaliar o Modelo (Árvore de Decisão)
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 1. Criar o nosso "Cérebro" Classificador
modelo_spam = DecisionTreeClassifier(random_state=42)

# 2. Treinar a IA com os texto em formato númerico e as respostas certas
modelo_spam.fit(X_treino_numeros, y_treino)

# 3. Fazer a prova final com os dados de teste (que a máquina nunca viu)
precisoes = modelo_spam.predict(X_teste_numeros)

# 4. Calcular a nota (Taxa de acerto / Acurácia)
nota = accuracy_score(y_teste, precisoes)
print(f"Taxa de acerto do modelo: {nota * 100}%!")

Taxa de acerto do modelo: 100.0%!

In [13]:
# 5. o filtro em Ação
meu_email_novo = ['Reunião com a equipe']

# 1. Traduzir o e-mail novo para matemática
meu_email_numeros = tradutor.transform(meu_email_novo)

# 2. Pedir para a IA classificar
resultado = modelo_spam.predict(meu_email_numeros)

if resultado[0] == 1:
    print("ALERTA: A IA classificou este e-mail como SPAM!")
else:
    print("SEGURO: A IA classificou este e-mail como normal!")

ALERTA: A IA classificou este e-mail como SPAM!

In [15]:
# 5. o filtro em Ação
meu_email_novo = ['Reunião com a equipe']

# 1. Traduzir o e-mail novo para matemática
meu_email_numeros = tradutor.transform(meu_email_novo)

# 2. Pedir para a IA classificar
resultado = modelo_spam.predict_proba(meu_email_numeros)

print(resultado)

[[0. 1.]]